branches:
  only:
    - staging
    - trying

environment:
  # use the most aggressive compressing because .gradle is HUGE
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma2 -mx=9
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  ORG_GRADLE_PROJECT_ideaVersion: 2018.1
  ORG_GRADLE_PROJECT_sinceBuild: 181

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs -FileName rustup-init.exe
  - rustup-init.exe -y
  - set PATH=C:\Users\appveyor\.cargo\bin;%PATH%
  - rustup component add rustfmt-preview

build_script:
  - gradlew.bat assemble testClasses --no-daemon

test_script:
  - gradlew.bat check --no-daemon

on_success:
  - ps: rm C:\Users\appveyor\.gradle\caches\modules-2\modules-2.lock -force
  - ps: rm C:\Users\appveyor\.gradle\caches\*\plugin-resolution\ -recurse -force
  - ps: rm C:\Users\appveyor\.gradle\caches\*\fileHashes\fileHashes.bin -force
  - ps: rm C:\Users\appveyor\.gradle\caches\*\fileHashes\fileHashes.lock -force

cache:
  - C:\Users\appveyor\.cargo\registry
  - C:\Users\appveyor\.cargo\bin
  - C:\Users\appveyor\.gradle
