---
# --- Variables --- #

local:
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

# --- Release Manager Config --- #

# Required: deployment targets
targets:
  - type              : "awss3"
    access_key_id     : <%= ENV['AWS_DEPLOY_ACCESS_KEY_ID'] %>
    secret_access_key : <%= ENV['AWS_DEPLOY_SECRET_ACCESS_KEY'] %>

# Required: packages to be deployed
packages:
  - name     : "clojure-collector-hosted-asset"
    locations:
    - bucket   : "snowplow-hosted-assets"
      path     : "2-collectors/clojure-collector"
      region   : "eu-west-1"
    - bucket   : "snowplow-hosted-assets-us-east-1"
      path     : "2-collectors/clojure-collector"
      region   : "us-east-1"
    - bucket   : "snowplow-hosted-assets-us-west-1"
      path     : "2-collectors/clojure-collector"
      region   : "us-west-1"
    - bucket   : "snowplow-hosted-assets-us-west-2"
      path     : "2-collectors/clojure-collector"
      region   : "us-west-2"
    - bucket   : "snowplow-hosted-assets-sa-east-1"
      path     : "2-collectors/clojure-collector"
      region   : "sa-east-1"
    - bucket   : "snowplow-hosted-assets-eu-central-1"
      path     : "2-collectors/clojure-collector"
      region   : "eu-central-1"
    - bucket   : "snowplow-hosted-assets-ap-southeast-1"
      path     : "2-collectors/clojure-collector"
      region   : "ap-southeast-1"
    - bucket   : "snowplow-hosted-assets-ap-southeast-2"
      path     : "2-collectors/clojure-collector"
      region   : "ap-southeast-2"
    - bucket   : "snowplow-hosted-assets-ap-northeast-1"
      path     : "2-collectors/clojure-collector"
      region   : "ap-northeast-1"
    - bucket   : "snowplow-hosted-assets-ap-south-1"
      path     : "2-collectors/clojure-collector"
      region   : "ap-south-1"
    - bucket   : "snowplow-hosted-assets-us-east-2"
      path     : "2-collectors/clojure-collector"
      region   : "us-east-2"
    - bucket   : "snowplow-hosted-assets-ca-central-1"
      path     : "2-collectors/clojure-collector"
      region   : "ca-central-1"
    - bucket   : "snowplow-hosted-assets-eu-west-2"
      path     : "2-collectors/clojure-collector"
      region   : "eu-west-2"
    - bucket   : "snowplow-hosted-assets-ap-northeast-2"
      path     : "2-collectors/clojure-collector"
      region   : "ap-northeast-2"
    publish  : true
    override : false
    continue_on_conflict : false
    version  : <%= CMD['cd 2-collectors/clojure-collector/java-servlet && echo "(System/getProperty \"clojure-collector.version\")" | lein repl | grep "^\".*" | sed -rn "s/\"([0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?)\"/\1/p" | xargs echo -n'] %>

    # Required IF '--check-version' is passed: will assert that both versions are the same
    build_version : <%= ENV['TRAVIS_BUILD_RELEASE_TAG'] %>

    # Optional: Build commands
    build_commands:
      - cd 2-collectors/clojure-collector/java-servlet && lein deps && lein aws && cd ../..

    # Required: Artifact. Version will be inserted between prefix and suffix
    artifacts:
      - type   : "asis"
        prefix : "clojure-collector-"
        suffix : "-standalone.war"
        binary_paths:
          - "2-collectors/clojure-collector/java-servlet/target/clojure-collector-{{ packages.0.build_version }}-standalone.war"
