# Goals of this configuration:
# * Support codecov informing us about where we need to improve
# * Drive overall code coverage up over the long term
# * Don't discourage contributors with Red X of Shame

coverage:
  status:
    project:
      # We want the project to be at least as well covered as
      # it was before, but we'll allow a 1% drop without incident,
      # because stuff happens.  It's on us to make sure we're
      # improving over the long haul.
      default:
        target: auto
        threshold: 1%
    patch:
      # Patch coverage is informative, so we leave it enabled.
      # But there are a lot of reasonable commits that don't affect
      # overall coverage while have dreadful patch metrics (e.g.,
      # reformatting).  Let's calculate this, but not punish it.
      # If we want more tests, a human should politely ask for them.
      default:
        target: 0%
    changes: no
