version: 2
jobs:
  # CLI publishing
  cli:
    docker:
      - image: circleci/node:8
      - image: circleci/postgres:10.3-alpine
        environment:
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prisma
          POSTGRES_PW: prisma
          POSTGRES_DB: prisma
    steps:
      - checkout
      - run: sudo apt install postgresql-client
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: cd cli && yarn
      - run:
          name: Waiting for PostgreSQL to start
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 2
            done
            echo Failed waiting for Postgres && exit 1
      - run: ./cli/scripts/publish.sh

  # content deployment
  content:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: sudo npm i -g @graphcool/docs-cli
      - run:
          command: .circleci/deploy-docs.sh || .circleci/deploy-docs.sh
          environment:
            BLUE_ID: cjce1hjzi0z1o01539nc8949x
            GREEN_ID: cjce1bhux0xwx0127k0ava9o4
            ALIAS: prisma-docs

workflows:
  version: 2
  build:
    jobs:
      - cli:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
                - beta
                - alpha
      - content:
          filters:
            branches:
              only:
                - master
