# Transient db - will lose it's data once restarted
version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    command: mysqld
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    ports:
      - "127.0.0.1:3306:3306"
