version: "2"
services:
  db:
    image: mysql:5.7
    command: mysqld
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $SQL_CLIENT_PASSWORD
      MYSQL_DATABASE: $SQL_INTERNAL_DATABASE
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - /Volumes/ramdisk/mysqldata:/var/lib/mysql

  rabbit:
    image: rabbitmq:3-management
    restart: always
    hostname: rabbit-host
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
